config/routes.rb
Rails.application.routes.draw do
  resources :item_designs
  resources :lace_designs

end

app/models/item_design.rb
class ItemDesign < ActiveRecord::Base
    belongs_to :lace_design
end

app/models/lace_design.rb
class LaceDesign < ActiveRecord::Base
    has_many :item_designs
    accepts_nested_attributes_for :item_designs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_designs_controller.rb
class ItemDesignsController < ApplicationController
  before_action :set_item_design, only: [:show, :edit, :update, :destroy]

  # GET /item_designs
  # GET /item_designs.json
  def index
    @item_designs = ItemDesign.all
  end

  # GET /item_designs/1
  # GET /item_designs/1.json
  def show
  end

  # GET /item_designs/new
  def new
    @item_design = ItemDesign.new
  end

  # GET /item_designs/1/edit
  def edit
  end

  # POST /item_designs
  # POST /item_designs.json
  def create
    @item_design = ItemDesign.new(item_design_params)

    respond_to do |format|
      if @item_design.save
        format.html { redirect_to @item_design, notice: 'Item design was successfully created.' }
        format.json { render :show, status: :created, location: @item_design }
      else
        format.html { render :new }
        format.json { render json: @item_design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_designs/1
  # PATCH/PUT /item_designs/1.json
  def update
    respond_to do |format|
      if @item_design.update(item_design_params)
        format.html { redirect_to @item_design, notice: 'Item design was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_design }
      else
        format.html { render :edit }
        format.json { render json: @item_design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_designs/1
  # DELETE /item_designs/1.json
  def destroy
    @item_design.destroy
    respond_to do |format|
      format.html { redirect_to item_designs_url, notice: 'Item design was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_design
      @item_design = ItemDesign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_design_params
      params.require(:item_design).permit(:item_cd, :yarn, :strech_rate, :ori_mr, :plan_width, :plan_repeart, :special_width, :special_repeart, :repeart_count, :process_type, :remarks, :lace_design_id)
    end
end

app/controllers/lace_designs_controller.rb
class LaceDesignsController < ApplicationController
  before_action :set_lace_design, only: [:show, :edit, :update, :destroy]

  # GET /lace_designs
  # GET /lace_designs.json
  def index
    @lace_designs = LaceDesign.all
  end

  # GET /lace_designs/1
  # GET /lace_designs/1.json
  def show
  end

  # GET /lace_designs/new
  def new
    @lace_design = LaceDesign.new
    @lace_design.item_designs.build
  end

  # GET /lace_designs/1/edit
  def edit
  end

  # POST /lace_designs
  # POST /lace_designs.json
  def create
    @lace_design = LaceDesign.new(lace_design_params)

    respond_to do |format|
      if @lace_design.save
        format.html { redirect_to @lace_design, notice: 'Lace design was successfully created.' }
        format.json { render :show, status: :created, location: @lace_design }
      else
        format.html { render :new }
        format.json { render json: @lace_design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lace_designs/1
  # PATCH/PUT /lace_designs/1.json
  def update
    respond_to do |format|
      if @lace_design.update(lace_design_params)
        format.html { redirect_to @lace_design, notice: 'Lace design was successfully updated.' }
        format.json { render :show, status: :ok, location: @lace_design }
      else
        format.html { render :edit }
        format.json { render json: @lace_design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lace_designs/1
  # DELETE /lace_designs/1.json
  def destroy
    @lace_design.destroy
    respond_to do |format|
      format.html { redirect_to lace_designs_url, notice: 'Lace design was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lace_design
      @lace_design = LaceDesign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lace_design_params
      params.require(:lace_design).permit(
        :lace_design_no, :use, :lace_type, :rs, :carry, :point, :nominal_width, :fin_mr, :mc_type, :honsu, :sherring, :halfcut, :skecher, :design_code, :design_no, :drafman, :remarks,
        item_designs_attributes: [:item_cd, :yarn, :strech_rate, :ori_mr, :plan_width, :plan_repeart, :special_width, :special_repeart, :repeart_count, :process_type, :remarks, :lace_design_id]
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_designs_helper.rb
module ItemDesignsHelper
end

app/helpers/lace_designs_helper.rb
module LaceDesignsHelper
end

app/views/item_designs/_form.html.erb
<%= form_for @item_design, :html => { :class => "form-horizontal item_design" } do |f| %>

  <% if @item_design.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@item_design.errors.count, "error") %> prohibited this item_design from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @item_design.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :item_cd, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :item_cd, :class => 'form-control' %>
    </div>
    <%=f.error_span(:item_cd) %>
  </div>
  <div class="form-group">
    <%= f.label :yarn, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :yarn, :class => 'form-control' %>
    </div>
    <%=f.error_span(:yarn) %>
  </div>
  <div class="form-group">
    <%= f.label :strech_rate, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :strech_rate, :class => 'form-control' %>
    </div>
    <%=f.error_span(:strech_rate) %>
  </div>
  <div class="form-group">
    <%= f.label :ori_mr, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ori_mr, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ori_mr) %>
  </div>
  <div class="form-group">
    <%= f.label :plan_width, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :plan_width, :class => 'form-control' %>
    </div>
    <%=f.error_span(:plan_width) %>
  </div>
  <div class="form-group">
    <%= f.label :plan_repeart, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :plan_repeart, :class => 'form-control' %>
    </div>
    <%=f.error_span(:plan_repeart) %>
  </div>
  <div class="form-group">
    <%= f.label :special_width, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :special_width, :class => 'form-control' %>
    </div>
    <%=f.error_span(:special_width) %>
  </div>
  <div class="form-group">
    <%= f.label :special_repeart, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :special_repeart, :class => 'form-control' %>
    </div>
    <%=f.error_span(:special_repeart) %>
  </div>
  <div class="form-group">
    <%= f.label :process_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :process_type, :class => 'form-control' %>
    </div>
    <%=f.error_span(:process_type) %>
  </div>
  <div class="form-group">
    <%= f.label :remarks, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :remarks, :class => 'form-control' %>
    </div>
    <%=f.error_span(:remarks) %>
  </div>
  <div class="form-group">
    <%= f.label :lace_design_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lace_design_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lace_design_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                item_designs_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/item_designs/edit.html.erb
<%- model_class = ItemDesign -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/item_designs/index.html.erb
<%- model_class = ItemDesign -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:item_cd) %></th>
      <th><%= model_class.human_attribute_name(:yarn) %></th>
      <th><%= model_class.human_attribute_name(:strech_rate) %></th>
      <th><%= model_class.human_attribute_name(:ori_mr) %></th>
      <th><%= model_class.human_attribute_name(:plan_width) %></th>
      <th><%= model_class.human_attribute_name(:plan_repeart) %></th>
      <th><%= model_class.human_attribute_name(:special_width) %></th>
      <th><%= model_class.human_attribute_name(:special_repeart) %></th>
      <th><%= model_class.human_attribute_name(:process_type) %></th>
      <th><%= model_class.human_attribute_name(:remarks) %></th>
      <th><%= model_class.human_attribute_name(:lace_design_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @item_designs.each do |item_design| %>
      <tr>
        <td><%= link_to item_design.id, item_design_path(item_design) %></td>
        <td><%= item_design.item_cd %></td>
        <td><%= item_design.yarn %></td>
        <td><%= item_design.strech_rate %></td>
        <td><%= item_design.ori_mr %></td>
        <td><%= item_design.plan_width %></td>
        <td><%= item_design.plan_repeart %></td>
        <td><%= item_design.special_width %></td>
        <td><%= item_design.special_repeart %></td>
        <td><%= item_design.process_type %></td>
        <td><%= item_design.remarks %></td>
        <td><%= item_design.lace_design_id %></td>
        <td><%=l item_design.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_design_path(item_design), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_design_path(item_design),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_design_path,
            :class => 'btn btn-primary' %>

app/views/item_designs/new.html.erb
<%- model_class = ItemDesign -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/item_designs/show.html.erb
<%- model_class = ItemDesign -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:item_cd) %>:</strong></dt>
  <dd><%= @item_design.item_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:yarn) %>:</strong></dt>
  <dd><%= @item_design.yarn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:strech_rate) %>:</strong></dt>
  <dd><%= @item_design.strech_rate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ori_mr) %>:</strong></dt>
  <dd><%= @item_design.ori_mr %></dd>
  <dt><strong><%= model_class.human_attribute_name(:plan_width) %>:</strong></dt>
  <dd><%= @item_design.plan_width %></dd>
  <dt><strong><%= model_class.human_attribute_name(:plan_repeart) %>:</strong></dt>
  <dd><%= @item_design.plan_repeart %></dd>
  <dt><strong><%= model_class.human_attribute_name(:special_width) %>:</strong></dt>
  <dd><%= @item_design.special_width %></dd>
  <dt><strong><%= model_class.human_attribute_name(:special_repeart) %>:</strong></dt>
  <dd><%= @item_design.special_repeart %></dd>
  <dt><strong><%= model_class.human_attribute_name(:process_type) %>:</strong></dt>
  <dd><%= @item_design.process_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remarks) %>:</strong></dt>
  <dd><%= @item_design.remarks %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lace_design_id) %>:</strong></dt>
  <dd><%= @item_design.lace_design_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              item_designs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_design_path(@item_design), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_design_path(@item_design),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/lace_designs/_form.html.erb
<%= form_for @lace_design, :html => { :class => "form-horizontal lace_design" } do |f| %>

  <% if @lace_design.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@lace_design.errors.count, "error") %> prohibited this lace_design from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @lace_design.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :lace_design_no, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lace_design_no, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lace_design_no) %>
  </div>
  <div class="form-group">
    <%= f.label :use, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :use, :class => 'form-control' %>
    </div>
    <%=f.error_span(:use) %>
  </div>
  <div class="form-group">
    <%= f.label :lace_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lace_type, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lace_type) %>
  </div>
  <div class="form-group">
    <%= f.label :rs, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :rs, :class => 'form-control' %>
    </div>
    <%=f.error_span(:rs) %>
  </div>
  <div class="form-group">
    <%= f.label :carry, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :carry, :class => 'form-control' %>
    </div>
    <%=f.error_span(:carry) %>
  </div>
  <div class="form-group">
    <%= f.label :point, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :point, :class => 'form-control' %>
    </div>
    <%=f.error_span(:point) %>
  </div>
  <div class="form-group">
    <%= f.label :nominal_width, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nominal_width, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nominal_width) %>
  </div>
  <div class="form-group">
    <%= f.label :fin_mr, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :fin_mr, :class => 'form-control' %>
    </div>
    <%=f.error_span(:fin_mr) %>
  </div>
  <div class="form-group">
    <%= f.label :mc_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mc_type, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mc_type) %>
  </div>
  <div class="form-group">
    <%= f.label :honsu, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :honsu, :class => 'form-control' %>
    </div>
    <%=f.error_span(:honsu) %>
  </div>
  <div class="form-group">
    <%= f.label :sherring, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sherring, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sherring) %>
  </div>
  <div class="form-group">
    <%= f.label :halfcut, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :halfcut, :class => 'form-control' %>
    </div>
    <%=f.error_span(:halfcut) %>
  </div>
  <div class="form-group">
    <%= f.label :skecher, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :skecher, :class => 'form-control' %>
    </div>
    <%=f.error_span(:skecher) %>
  </div>
  <div class="form-group">
    <%= f.label :design_code, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :design_code, :class => 'form-control' %>
    </div>
    <%=f.error_span(:design_code) %>
  </div>
  <div class="form-group">
    <%= f.label :design_no, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :design_no, :class => 'form-control' %>
    </div>
    <%=f.error_span(:design_no) %>
  </div>
  <div class="form-group">
    <%= f.label :drafman, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :drafman, :class => 'form-control' %>
    </div>
    <%=f.error_span(:drafman) %>
  </div>
  <div class="form-group">
    <%= f.label :remarks, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :remarks, :class => 'form-control' %>
    </div>
    <%=f.error_span(:remarks) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lace_designs_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/lace_designs/edit.html.erb
<%- model_class = LaceDesign -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lace_designs/index.html.erb
<%- model_class = LaceDesign -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="col-lg-3">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_lace_design_path,
              :class => 'btn btn-primary' %>
</div>

<table class="col-lg-12 table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:lace_design_no) %></th>
      <th><%= model_class.human_attribute_name(:skecher) %></th>
      <th><%= model_class.human_attribute_name(:design_code) %></th>
      <th><%= model_class.human_attribute_name(:design_no) %></th>
      <th><%= model_class.human_attribute_name(:use) %></th>
      <th><%= model_class.human_attribute_name(:lace_type) %></th>
      <th><%= model_class.human_attribute_name(:rs) %></th>
      <th><%= model_class.human_attribute_name(:carry) %></th>
      <th><%= model_class.human_attribute_name(:point) %></th>
      <th><%= model_class.human_attribute_name(:nominal_width) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lace_designs.each do |lace_design| %>
      <tr>
        <td><%= link_to lace_design.id, lace_design_path(lace_design) %></td>
        <td><%= lace_design.lace_design_no %></td>
        <td><%= lace_design.use %></td>
        <td><%= lace_design.lace_type %></td>
        <td><%= lace_design.rs %></td>
        <td><%= lace_design.carry %></td>
        <td><%= lace_design.point %></td>
        <td><%= lace_design.nominal_width %></td>
        <td><%= lace_design.fin_mr %></td>
        <td><%= lace_design.mc_type %></td>
        <td><%= lace_design.honsu %></td>
        <td><%= lace_design.sherring %></td>
        <td><%= lace_design.halfcut %></td>
        <td><%= lace_design.skecher %></td>
        <td><%= lace_design.design_code %></td>
        <td><%= lace_design.design_no %></td>
        <td><%= lace_design.drafman %></td>
        <td><%= lace_design.remarks %></td>
        <td><%=l lace_design.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_lace_design_path(lace_design), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      lace_design_path(lace_design),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lace_designs/new.html.erb
<%- model_class = LaceDesign -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lace_designs/show.html.erb
<%- model_class = LaceDesign -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:lace_design_no) %>:</strong></dt>
  <dd><%= @lace_design.lace_design_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:use) %>:</strong></dt>
  <dd><%= @lace_design.use %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lace_type) %>:</strong></dt>
  <dd><%= @lace_design.lace_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rs) %>:</strong></dt>
  <dd><%= @lace_design.rs %></dd>
  <dt><strong><%= model_class.human_attribute_name(:carry) %>:</strong></dt>
  <dd><%= @lace_design.carry %></dd>
  <dt><strong><%= model_class.human_attribute_name(:point) %>:</strong></dt>
  <dd><%= @lace_design.point %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nominal_width) %>:</strong></dt>
  <dd><%= @lace_design.nominal_width %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fin_mr) %>:</strong></dt>
  <dd><%= @lace_design.fin_mr %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mc_type) %>:</strong></dt>
  <dd><%= @lace_design.mc_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:honsu) %>:</strong></dt>
  <dd><%= @lace_design.honsu %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sherring) %>:</strong></dt>
  <dd><%= @lace_design.sherring %></dd>
  <dt><strong><%= model_class.human_attribute_name(:halfcut) %>:</strong></dt>
  <dd><%= @lace_design.halfcut %></dd>
  <dt><strong><%= model_class.human_attribute_name(:skecher) %>:</strong></dt>
  <dd><%= @lace_design.skecher %></dd>
  <dt><strong><%= model_class.human_attribute_name(:design_code) %>:</strong></dt>
  <dd><%= @lace_design.design_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:design_no) %>:</strong></dt>
  <dd><%= @lace_design.design_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:drafman) %>:</strong></dt>
  <dd><%= @lace_design.drafman %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remarks) %>:</strong></dt>
  <dd><%= @lace_design.remarks %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              lace_designs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lace_design_path(@lace_design), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lace_design_path(@lace_design),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>